[global]
author         = "jgrelet IRD july 2015 CASSIOPEE cruise"
debug          = false
echo           = true

[cruise]
cycleMesure    = "CASSIOPEE"
plateforme     = "ATALANTE"
callsign       = "FNCM"
institute      = "IRD"
pi             = "MARIN"
timezone       = "GMT"
beginDate      = "19/07/2015"
endDate        = "23/08/2015"
creator        = "Jacques.Grelet_at_ird.fr"

[ctd]
cruisePrefix   = "csp"
stationPrefixLength  = 5
titleSummary  = "CTD profiles processed during CASSIOPEE cruise"
typeInstrument   = "SBE911+"
instrumentNumber  = "09P29544-0694"
split          = "PRES,3,DEPTH,4,ETDD,2,TEMP,5,PSAL,22,DENS,24,SVEL,26,DOX2,19,FLU2,14,TUR3,13,LGH3,15,NUMP,18,NAVG,21"

splitAll       = "PRES,3,DEPTH,4,ETDD,2,TE01,5,TE02,6,PSA1,22,PSA2,23,DO12,19,DO22,20,DEN1,24,DEN2,25,SVEL,26,CND1,7,CND2,8,DOV1,9,DVT1,10,DOV2,11,DVT2,12,TUR3,13,FLU2,14,LGH3,15,LGHT,16,LGH4,17,NUMP,18,NAVG,21"

[btl]
cruisePrefix   = "csp"
stationPrefixLength  = 5
typeInstrument = "SBE32 standard 22 Niskin bottles"
instrumentNumber  = "unknown"
titleSummary  = "Water sample during cruise with 22 levels"
comment        = "CTD bottles water sampling with temperature, salinity and oxygen from primary and secondary sensors"
split = "BOTL,1,PSA1,5,PSA2,6,DO11,7,DO21,8,PRES,14,DEPTH,15"
#split = "BOTL,1,PSA1,5,PSA2,6,DO11,7,DO21,8,DO12,9,DO22,10,Potemp090C,11,Potemp190C,12,ETDD,13,PRES,14,DEPH,15,TE01,16,TE02,17,CND1,18,CND2,19,DOV1,20,DVT1,21,DOV2,23,DVT2,23,TUR3,24,FLU2,25,,LGH3,26,LGHT,27,LGH4,28,NUMP,29"

