[global]
author         = "jgrelet IRD march 2014 PIRATA-FR24 cruise"
debug          = false
echo           = true

[cruise]
cycleMesure    = "PIRATA-FR24"
plateforme     = "LE SUROIT"
callsign       = "FNCM"
imo            = "8716071"
mmsi           = "227222000"
context        = "AMMA"
timezone       = "GMT"
formatDate     = "DMY"
processingCode = "1A"
beginDate      = "09/04/2014"
endDate        = "21/05/2014"
institute      = "IRD"
pi             = "BOURLES"
creator        = "Jacques.Grelet@ird.fr"

[xml]
# dtd = local or public
dtd            = "public"
dtdLocalPath   = "/m/PIRATA-FR24"
#encoding      = "ISO-8859-1"
encoding       = "UTF-8"

[ctd]
cruisePrefix   = "fr24"
# profile name : fr24xxx
stationPrefixLength  = 3
acquisitionSoftware = "SEASAVE"
acquisitionVersion = "7.22.3"
processingSoftware = "SBE-PROCESSING"
processingVersion = "7.22.3"
typeInstrument    = "SBE911+"
instrumentNumber  = "1209"
titleSummary   = "CTD profiles processed during PIRATA-FR24 cruise"
comment        = "CTD profiles with pre-cruise coefficients, temperature, salinity and oxygen from primary and secondary sensors"
split          = "PRES,3,DEPTH,4,ETDD,2,TEMP,5,PSAL,18,DENS,20,SVEL,22,DOX2,15,FLU2,13,TUR3,14,NAVG,17"
odvHdr         = "PRES  TEMP    PSAL   DENS   SVEL     DOX2     FLU2"
odvUnit        = "[db]  [C]    [Psu]  [kg/m3] [m/s] [micromole/kg] [milligram/m3]"

[ctd-all]
header         = "PRFL  PRES   DEPTH   ETDD      TE01    TE02     PSA1    PSA2    CND1    CND2   DEN1   DEN2   SVEL    FLU2   TUR3   DO12   DO22    DOV1  DOV2     DVT1     DVT2   NAVG"
split          = "ETDD,2,PRES,3,DEPTH,4,TE01,5,TE02,6,CND1,7,CND2,8,DOV1,9,DOV2,10,DVT1,11,DVT2,12,FLU2,13,TUR3,14,DO12,15,DO22,16,NAVG,17,PSA1,18,PSA2,19,DEN1,20,DEN2,21,SVEL,22"

[btl]
type           = "SBE32 standard 12 Niskin bottles"
sn             = "unknown"
titleSummary   = "Water sample during PIRATA-FR24 cruise with 11 levels"
comment        = "CTD bottles water sampling with temperature, salinity and oxygen from primary and secondary sensors"
split = "BOTL,1,month,2,day,3,year,4,PSA1,5,PSA2,6,DO11,7,DO21,8,DO12,9,DO22,10,Potemp090C,11,Potemp190C,12,ETDD,13,PRES,14,DEPTH,15,TE01,16,TE02,17,CND1,18,CND2,19,DOV1,20,DOV2,21,DVT1,22,DVT2,23,FLU2,24"
header = "PRFL  BOTL PRES  DEPTH     ETDD     TE01    TE02     PSA1    PSA2   CND1     CND2    DO11    DO21      DO12    DO22     DOV1    DOV2      DVT1    DVT2    FLU2    Potemp090C Potemp190C"
format = "%05d  %2d %6.1f %6.1f %10.6f %7.4f %7.4f  %7.4f %7.4f %7.5f %7.5f %7.4f %7.4f  %8.3f %8.3f %8.5f %8.5f %+7.5f %+7.5f %+6.4f   %7.4f   %7.4f"

[xbt]
cruisePrefix   = "fr24" 
stationPrefixLength  = 3
acquisitionSoftware = "WinMK21"
acquisitionVersion = "2.10.1" 
processingSoftware = ""
processingVersion = ""
type           = "SIPPICAN"
sn             = "01150"
titleSummary   = "XBT profiles processed during PIRATA-FR24 cruise"
comment        = "Extract from .edf files"

[thermo]
cruisePrefix   = "fr24"
stationPrefixLength  = ""
acquisitionSoftware = "THECSAS"
acquisitionVersion = ""
processingSoftware = ""
processingVersion = ""
type           = "SBE21"
sn             = "3223"
calDate        = "17/12/2009"
externalType   = "SBE3S"
externalSn     = "4075"
externalCalDate = "19/04/2011"
depthIntake    = 4
titleSummary   = "Thermosalinograph data acquired with Seabird SBE21 instrument and reduce with THECSAS/COLCOR"
comment        = "Extract from .colcor files"

[ladcp]
cruisePrefix   = "fr24"
# profile name : "fr24xxx"
stationPrefixLength  = 3
acquisitionSoftware = "BBTALK"
acquisitionVersion = "3.04"
processingSoftware = "MATLAB-VISBECK"
processingVersion = "10.16.2"
type           = "WH300"
sn             = "12818"
titleSummary   = "IFM-GEOMAR/LDEO Matlab LADCP-Processing system adapted by FM/JG"
comment        = "Extract from .lad files"

[sadcp]
type           = "BB150"

